<?php
declare(strict_types=1);

return [
    'clients' => [
        'table' => 'clients',
        'primary' => 'id',
        'fields' => [
            'name' => ['label' => 'Client Name', 'type' => 'text', 'required' => true],
            'contact_person' => ['label' => 'Contact Person', 'type' => 'text', 'required' => true],
            'contact_email' => ['label' => 'Contact Email', 'type' => 'email', 'required' => true],
            'contact_phone' => ['label' => 'Contact Phone', 'type' => 'text', 'required' => false],
        ],
        'tenant_scoped' => false,
        'roles' => ['Admin'],
    ],
    'users' => [
        'table' => 'users',
        'primary' => 'id',
        'fields' => [
            'full_name' => ['label' => 'Full Name', 'type' => 'text', 'required' => true],
            'email' => ['label' => 'Email', 'type' => 'email', 'required' => true],
            'role' => ['label' => 'Role', 'type' => 'select', 'options' => ['Admin','Manager','Engineer'], 'required' => true],
            'client_id' => ['label' => 'Client', 'type' => 'relation', 'source' => 'clients', 'required' => false],
            'password' => ['label' => 'Password', 'type' => 'password', 'required' => false],
        ],
        'tenant_scoped' => false,
        'roles' => ['Admin'],
    ],
    'projects' => [
        'table' => 'projects',
        'primary' => 'id',
        'fields' => [
            'name' => ['label' => 'Project Name', 'type' => 'text', 'required' => true],
            'description' => ['label' => 'Description', 'type' => 'textarea', 'required' => false],
            'start_date' => ['label' => 'Start Date', 'type' => 'date', 'required' => true],
            'end_date' => ['label' => 'End Date', 'type' => 'date', 'required' => false],
            'budget' => ['label' => 'Budget', 'type' => 'number', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager','Engineer'],
    ],
    'tasks' => [
        'table' => 'tasks',
        'primary' => 'id',
        'fields' => [
            'project_id' => ['label' => 'Project', 'type' => 'relation', 'source' => 'projects', 'required' => true],
            'title' => ['label' => 'Task Title', 'type' => 'text', 'required' => true],
            'assigned_to' => ['label' => 'Assigned To', 'type' => 'text', 'required' => false],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Pending','In Progress','Completed'], 'required' => true],
            'due_date' => ['label' => 'Due Date', 'type' => 'date', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager','Engineer'],
    ],
    'boq' => [
        'table' => 'boq_items',
        'primary' => 'id',
        'fields' => [
            'project_id' => ['label' => 'Project', 'type' => 'relation', 'source' => 'projects', 'required' => true],
            'item_code' => ['label' => 'Item Code', 'type' => 'text', 'required' => true],
            'description' => ['label' => 'Description', 'type' => 'textarea', 'required' => true],
            'unit' => ['label' => 'Unit', 'type' => 'text', 'required' => true],
            'quantity' => ['label' => 'Quantity', 'type' => 'number', 'required' => true],
            'rate' => ['label' => 'Rate', 'type' => 'number', 'required' => true],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager'],
    ],
    'dpr' => [
        'table' => 'daily_progress_reports',
        'primary' => 'id',
        'fields' => [
            'project_id' => ['label' => 'Project', 'type' => 'relation', 'source' => 'projects', 'required' => true],
            'report_date' => ['label' => 'Report Date', 'type' => 'date', 'required' => true],
            'summary' => ['label' => 'Summary', 'type' => 'textarea', 'required' => true],
            'quantity_completed' => ['label' => 'Quantity Completed', 'type' => 'number', 'required' => false],
            'photo' => ['label' => 'Photo', 'type' => 'file', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager','Engineer'],
    ],
    'material_requests' => [
        'table' => 'material_requests',
        'primary' => 'id',
        'fields' => [
            'project_id' => ['label' => 'Project', 'type' => 'relation', 'source' => 'projects', 'required' => true],
            'material_name' => ['label' => 'Material', 'type' => 'text', 'required' => true],
            'quantity' => ['label' => 'Quantity', 'type' => 'number', 'required' => true],
            'needed_by' => ['label' => 'Needed By', 'type' => 'date', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Pending','Approved','Rejected'], 'required' => true],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager'],
    ],
    'purchase_orders' => [
        'table' => 'purchase_orders',
        'primary' => 'id',
        'fields' => [
            'vendor_id' => ['label' => 'Vendor', 'type' => 'relation', 'source' => 'vendors', 'required' => true],
            'order_date' => ['label' => 'Order Date', 'type' => 'date', 'required' => true],
            'total_amount' => ['label' => 'Total Amount', 'type' => 'number', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Draft','Issued','Completed'], 'required' => true],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager'],
    ],
    'stock' => [
        'table' => 'stock_ledger',
        'primary' => 'id',
        'fields' => [
            'material_name' => ['label' => 'Material', 'type' => 'text', 'required' => true],
            'transaction_type' => ['label' => 'Type', 'type' => 'select', 'options' => ['In','Out'], 'required' => true],
            'quantity' => ['label' => 'Quantity', 'type' => 'number', 'required' => true],
            'reference' => ['label' => 'Reference', 'type' => 'text', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager'],
    ],
    'attendance' => [
        'table' => 'attendance_logs',
        'primary' => 'id',
        'fields' => [
            'work_date' => ['label' => 'Date', 'type' => 'date', 'required' => true],
            'employee_name' => ['label' => 'Employee', 'type' => 'text', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Present','Absent','Leave'], 'required' => true],
            'shift' => ['label' => 'Shift', 'type' => 'text', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager','Engineer'],
    ],
    'workforce' => [
        'table' => 'workforce',
        'primary' => 'id',
        'fields' => [
            'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
            'trade' => ['label' => 'Trade', 'type' => 'text', 'required' => true],
            'joined_on' => ['label' => 'Joined On', 'type' => 'date', 'required' => true],
            'rate' => ['label' => 'Rate', 'type' => 'number', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager'],
    ],
    'equipment' => [
        'table' => 'equipment_logs',
        'primary' => 'id',
        'fields' => [
            'equipment_name' => ['label' => 'Equipment', 'type' => 'text', 'required' => true],
            'usage_date' => ['label' => 'Date', 'type' => 'date', 'required' => true],
            'hours_used' => ['label' => 'Hours Used', 'type' => 'number', 'required' => true],
            'project_id' => ['label' => 'Project', 'type' => 'relation', 'source' => 'projects', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager','Engineer'],
    ],
    'vendors' => [
        'table' => 'vendors',
        'primary' => 'id',
        'fields' => [
            'name' => ['label' => 'Vendor Name', 'type' => 'text', 'required' => true],
            'contact_person' => ['label' => 'Contact Person', 'type' => 'text', 'required' => false],
            'phone' => ['label' => 'Phone', 'type' => 'text', 'required' => false],
            'email' => ['label' => 'Email', 'type' => 'email', 'required' => false],
            'category' => ['label' => 'Category', 'type' => 'text', 'required' => false],
        ],
        'tenant_scoped' => true,
        'roles' => ['Admin','Manager'],
    ],
];
